.TH aptosid-irc "3" "January 2015" "aptosid-irc [OPTIONS]" "User Commands (1)"
.SH NAME
aptosid-irc - simple wrapper for joining #aptosid using an installed IRC client
.SH SYNOPSIS
.B aptosid-irc
[\fIOPTIONS\fR]
.SH DESCRIPTION
`aptosid-irc', is a wrapper to join the #aptosid IRC channel with any of the
supported installed IRC clients. Unless told otherwise, it prefers X11 based
IRC clients. Existing configurations for the chosen IRC client will not be touched.
.TP
\-\-tty
Use a textmode IRC client, like irssi or weechat, instead of a X11 based one.
.SH "SEE ALSO"
.BR irssi
.BR weechat-curses
.BR konversation
.BR xchat
.SH AUTHOR
This manual has been written by Stefan Lippers-Hollmann <s.l-h@gmx.de> for 
the Debian project (but may be used by others).
